"""This file is a second migration file for chat app."""

# Generated by Django 4.2.1 on 2023-05-26 12:18

from django.db import migrations


class Migration(migrations.Migration):
    """
    This class is migration class for a user, room and chat model.
    """

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='to_user',
        ),
    ]
